### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ncou** [spiral/boot#1]
Hi, nice piece of code. I am thinking to make my own micro-framework and you work is a good source of inspiration.

Looking at the code i think i have found a few typo : 

You need to change the sentense "....Must be executed before start method." with "... before serve method." I think there was previously a "start" function who have been renamed.
https://github.com/spiral/boot/blob/master/src/AbstractKernel.php#L110

The Directories interface docbloc indicate the "set()" method could throw a DirectoryException but it's not the case. I think it's a wrong copy/paste of the get() docbloc.
https://github.com/spiral/boot/blob/master/src/DirectoriesInterface.php#L29

Why use a "protected" function in a "final class" ? I think it should be a private function because you can't extend a final class. Am i missing something ?
https://github.com/spiral/boot/blob/master/src/Environment.php#L77

Teel me if a PR is needed.

**Comment by wolfy-j** [comment]
Hi, thank you for your feedback. Most of the code in this repository was not marked as final till last few months, so "protected" methods are rudiment which we are going to polish over time.

> You need to change the sentense "....Must be executed before start method." with "... before serve method." I think there was previously a "start" function who have been renamed.
https://github.com/spiral/boot/blob/master/src/AbstractKernel.php#L110

Fixed.

> The Directories interface docbloc indicate the "set()" method could throw a DirectoryException but it's not the case. I think it's a wrong copy/paste of the get() docbloc.
https://github.com/spiral/boot/blob/master/src/DirectoriesInterface.php#L29

In the past we have been throwing an exception if the directory already exists. Going forward we might add some error checking logic, it's ok to have exception notice even without an exception in our opinion.

**Comment by ncou** [comment]
happy to help :+1:
